CREATE TABLE NORMAL_TABLE (
                              ID NUMBER(20,0),
                              DATACREAZIONE DATE,
                              DATAMODIFICA DATE,
                              IDSTATO NUMBER(20,0),
                              NOTE VARCHAR(4000)
);

ALTER TABLE NORMAL_TABLE ADD CONSTRAINT NORMAL_TABLE_PK PRIMARY KEY ( ID );

CREATE SEQUENCE NORMAL_TABLE_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 10000000000
    NOCYCLE
  CACHE 1000
  ORDER;

CREATE BLOCKCHAIN TABLE BLOCKCHAIN_TABLE (
	ID NUMBER(20,0),
	DATACREAZIONE DATE,
	DATAMODIFICA DATE,
	IDSTATO NUMBER(20,0),
	NOTE VARCHAR(4000)
) NO DROP UNTIL 1 DAYS IDLE
     NO DELETE UNTIL 16 DAYS AFTER INSERT
     HASHING USING "SHA2_512" VERSION v2;

ALTER TABLE BLOCKCHAIN_TABLE ADD CONSTRAINT BLOCKCHAIN_TABLE_PK PRIMARY KEY ( ID );

CREATE SEQUENCE BLOCKCHAIN_TABLE_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 10000000000
    NOCYCLE
  CACHE 1000
  ORDER;